### PR TITLE
Update with v6.3

### LINKED ISSUE #56: startlongtable not respecting table centering rules in deluxetable.
From: https://tex.stackexchange.com/questions/393150/centering-a-very-wide-deluxetable

There appears to be a bug in the \startlongtable that prevents the normal behavior of deluxetable to center the table and overflow both the left and right margins equally. I can show it to be independent of style (tested for modern and preprint).

### LINKED ISSUE #57: twocolumn/text out of bounds
Hi,

I'm having problems keeping hyphenated words, inline equations, and hyperlinks within the boundaries of the column (at least when using the twocolumn option) for AASTeX v6.1.
I haven't seen this happening in v6.0/preprint2, so it seems to be something related to v6.1.

Here's a minimal example:

``` latex
\documentclass[tighten, times, twocolumn]{aastex61}
\begin{document}

\title{A bug report using aastex v6.1}
\author{Patricio}

\section{Introduction}

This is a normal piece of text showing the length of a column,
everything is good so far.  Actually, many thanks to everyone in the
the AASTeX developer team.

However, sometimes the twocolumn option misses hyphenated-word boundaries.

Some inline equations also break, e.g., $\gamma=0.071
(T/2000)^{-0.7}$ cm$^{-1}$ atm$^{-1}$.
\end{document}
```
And here's the output: http://geco.oeaw.ac.at/patricio/subdir/aastex/sample61.pdf

### LINKED ISSUE #63: tablehead centering with deluxetable
It seems that `deluxetable` isn't centering the final column header and unit properly in the last table column. This is only really noticeable with short column headers, and centering is restored by adding a line break after the unit for the last column (but then you have an extra line break...).

miscenter_example

Which results from this tex file:
```
\documentclass{aastex61}
\begin{document}

\begin{deluxetable*}{l ccccc }
\tablecolumns{13}
\tablewidth{0pt}
\tabletypesize{\footnotesize}
\tablehead{
Name & $x_1,y_1,z_1$ & $x_2,y_2,z_2$ & ${\rm R_{GC}}$ & col \\
 & (kpc) & (kpc) & (kpc) & (deg) 
}
\startdata
Data Goes Here     & \ldots  & \ldots & \ldots & \ldots \\
\enddata
\end{deluxetable*}

\begin{deluxetable*}{l ccccc }
\tablecolumns{13}
\tablewidth{0pt}
\tabletypesize{\footnotesize}
\tablehead{
Name & $x_1,y_1,z_1$ & $x_2,y_2,z_2$ & ${\rm R_{GC}}$ & col \\
 & (kpc) & (kpc) & (kpc) & (deg) \\
}
\startdata
Data Goes Here     & \ldots  & \ldots & \ldots & \ldots \\
\enddata
\end{deluxetable*}

\vfill Fill space ...
\clearpage
\end{document}
```

### LINKED ISSUE #68: New Feature: anonymize authors/affiliations from compiled PDF
Include an option to expunge author/affiliations from the compiled PDF. 

`\documentclass[noauthors]{modern}`

the `noauthors` option would replace the authors/affiliations block with either:

* nothing at all.
* Text that indicates that the author list was expunged

Other thoughts?

### LINKED ISSUE #72: navigation window for pdfs
It is a nice feature to have an article's sections show up in the navigation pane of PDF viewers. Supposedly this can be achieved by simply adding `\usepackage{hyperref}` to the end of the preamble (https://tex.stackexchange.com/questions/42343), but it doesn't seem to work with AASTeX. Not essential, but it would be awesome if it did work, especially for  really long articles! I suspect AASTeX might redefine the section commands in a way that breaks `hyperref`. Even better than having to use `hyperref` would  be if AASTeX automatically generated what is needed for the navigation pane. 

Below is an MWE. If the document class is changed from `aastex62` to `article`, then the generated PDF will show the section headings in a navigation pane. (Make sure to delete the intermediate files before regenerating a PDF.) 

```
\documentclass{aastex62}
\usepackage{hyperref}

\begin{document}

\section{Intro}
``The man in black fled across the desert, and the gunslinger followed.'' So begins Stephen King's \textit{Dark Tower} series.

\section{Body}
The series is quite long. 

\section{Conclusions}
I recommend listening to the series as an audiobook on cross-country drives. 

\end{document}
```

### LINKED ISSUE #74: startlongtable in appendices
I have some long tables in an appendix.  The tables appear fine.  However, after the first longtable, the appendix changes from one-column to two-column format.  I assume this is a bug.  For the moment, I'm getting around this by just putting the long tables at the end of of the appendix.

### LINKED ISSUE #75: Table Appendix Labeling
An author asserts that old versions of AASTeX (or maybe plain article latex) could be crafted so that a Table in the appendix is labeled, "A1" etc. AASTeX v6.2 appears to prevent this labeling.

I can't confirm if this assertion is true or not or if there is a bug where the table is floating away  from the label renewcommands or if AASTeX is disabling the label or what. This definitely need more work 

Our nominal style is to **continue Table numbering from the main text into the appendix** so even if this were a bug it is a bug that acts according to our style. sort of.

### LINKED ISSUE #76: \tablebreak adds additional blank line after break
The use of `\tablebreak` to put a page break in a rotated table (specifically, in my case, a `deluxetable` in a `longrotatetable` environment) adds an extra blank line after the break. As an example, if I do:

```latex
\documentclass[twocolumn]{aastex62}

\begin{document}

\title{Test \texttt{$\backslash$tablebreak}}
\author{Matthew Pitkin}
\date{December 2018}

\startlongtable
\begin{longrotatetable}
\begin{deluxetable}{cc}
\tablehead{\colhead{a} & \colhead{b}}
\startdata
1 & 2 \\
3 & 4 \\
5 & 6 \\
7 & 8
\enddata
\end{deluxetable}
\end{longrotatetable}

\startlongtable
\begin{longrotatetable}
\begin{deluxetable}{cc}
\tablehead{\colhead{a} & \colhead{b}}
\startdata
1 & 2 \\
3 & 4 \\
\tablebreak
5 & 6 \\
7 & 8
\enddata
\end{deluxetable}
\end{longrotatetable}

\end{document}
```
I get the extra blank line after the space.

If I change the definition of the `\tablebreak` macro from

```latex
\newcommand\tablebreak{\\[-11pt]\noalign{\break}}
```

to

```latex
\newcommand\tablebreak{\\[-11pt]\noalign{\break}}
```
the line is removed. Is the blank line "supposed" to be there, or can it be removed?

Also, I think in the [docs](https://journals.aas.org/aastexguide/#tables) it should say `\tablebreak rather than `\\tablebreak`.

### LINKED ISSUE #77: RNAAS option puts page break before references
Throwing the rnaas option in the \documentclass[rnaas]{aastex62} call creates an extra page to the document containing only the references, even if there is room on the previous page to hold them.

This is a very minor issue, but it seems unintentional and has the ironic effect of adding 50-100% to the page count of Research Notes.

### LINKED ISSUE #78: Update template to use only bibtex & add software/data citations
We should update the AASTeX template references to be 100% based on bibtex and to provide concrete bibtex+bst reference examples for software/data. @aaccomazzi made this point, and it is relevant for the [Asclepias project](https://github.com/asclepias) updates to ADS.  The motivations for this are:

1. As we ask authors to cite additional types of research objects (software/data), the style to properly capture and markup these references will depend more and more on bibtex input (+bibtex or biber style files);

2. BibTeX allows authors to make style choices (such as ignoring our request to list 3 authors + et al. and favoring First Author et al.)) that can be easily undone for submission/style requirements. 

3. It allows us to express our preference for bibtex. bibtex type input is also a requirement for moving away from natbib towards a biblatex/biber future. 

This issue includes both porting to use bibtex and updating this block -- [sample62.tex#L1186-L1210](https://github.com/AASJournals/AASTeX60/blob/master/sample/sample62.tex#L1186-L1210) -- to include a software and a data reference in the bibliography. Right now it only mentions  software objects but fails to give any example(s). 

A public library of ADS entries currently used in the AASTeX template references can be found here:

https://ui.adsabs.harvard.edu/#/public-libraries/y9y6esA1TOqAU3ynzYy-mA

Blockers:

* there are no software/data references in that example library as these are not fully indexed into ADS yet. After the release timed for the AAS233 meeting we should be able to find good examples in ADS to use in the bibliography for the template.

### LINKED ISSUE #81: Style of mark in tablenotetext doesn't match style of tablenotemark
When specifying a `\tablenotemark` in a table, one typeface is used, but in the `\tablenotetext` that follows, specifying the same symbol makes it appear with a different typeface.

Even in the sample – in tables 1 and 2 – the style of the mark at the `\tablenotetext` is different from the `\tablenotemark`.

### PR DESCRIPTION
**Pull request by augustfly**
This updates the files to v6.3 on GitHub (original release on July 10, 2019). 

@gregschwarz We need to make a list of which issues are closed by this PR. The AASTeX history page doesn't have the updated feature/bugs listed yet for v6.3 so I'm not clear on which are closed. Once we know about them I can add them to the list below so they will auto close when you accept the PR. These are the ones I'm sure about:

closes #56
closes #57 
closes #63
closes #68 
closes #70
closes #72
closes #74 
closes #75 
closes #76
closes #77
closes #78 
closes #81

I tried looking through the CLS file for documentation of which issues were closed, but I couldn't find enough detail in Amy's comments to make me 100% sure of anything.

### CODE REVIEW

**Comment by augustfly** [comment]
definitely closes #78

**Comment by augustfly** [comment]
Here is my "I think" list of issues to be closed. Let me know if I'm right but if I'm wrong then I'll need to delete this before we accept the PR. Of course add more if you know about them. 

closes #72 : enforces TOC for accessibility 
closes #74 : I hope? This is a nasty little bug. 
closes #76 : by accepting the solution already implemented in PR 79
closes #81 : i see a modification of the table note mark style in the new CLS. 
closes #83 : I thought we'd discuss this extensively.

**Comment by augustfly** [comment]
@gregschwarz Can you go through the AASTeX repo issues and list (in this thread) which ones are closed by v6.3?  Then I'll update the pull request thread and have you accept the PR. I can go through them after that and finalize any more that are outstanding.

**Comment by gregschwarz** [comment]
I can confirm that all of the issues mentioned in this thread are addressed in v6.3 with two exceptions. Issue #61 is a conflict between v6.2 and the siunitx.sty package. These can be tricky as common names can be used in different packages, in this case \tablenum, and there is no way to anticipate what will conflict with AASTeX. In the new v6.3 author guide we have some help for authors that [run into this specific siunitx.sty problem](https://journals.aas.org/aastexguide/#conflicts).

We will continue to document other solutions as they arise. The other exception is issue #83 which unfortunately I forgot to add to the requirements page that was sent to our LaTeX programmer. We should keep this open for the next version.

**Comment by augustfly** [comment]
Okay, I will manually comment on #61 and #83 after we merge. I think you can go ahead @gregschwarz

**Pull request merged**
