### PR TITLE
use newtx for the times option

### PR DESCRIPTION
**Pull request by yymao**
newtx (https://www.ctan.org/pkg/newtx) is an updated package that provides times font to botht the text and math, with better metrics.

### CODE REVIEW

**Comment by augustfly** [comment]
@gregschwarz Isn't newtx the package that has caused MNRAS's style file the widely mentioned (on facebook and elsewhere) horrors for arXiv submission? 

Yeah here it is: <http://tex.stackexchange.com/questions/251405/problem-with-new-mnras-style-files-newtx-on-arxiv>

**Comment by yymao** [comment]
Oh, thanks for this info!

**Comment by augustfly** [comment]
Since I don't see a fix for dealing with txfonts on arXiv, i'm going to close this for now. thanks tho!

**Comment by syrte** [comment]
It's OK to use newtx for arxiv now, as the update of https://tex.stackexchange.com/questions/251405/problem-with-new-mnras-style-files-newtx-on-arxiv  says
> Update: on February 10th, 2017, the TeX processing system of arXiv has been updated to TeX Live 2016, so this should be no more an issue.

**Pull request closed without merging**
