### PR TITLE
Fix sample.tex

### PR DESCRIPTION
**Pull request by adam-m-jcbs**
In this pull request, I fix some typos in the illustrative `sample.tex` document and resulting compiled PDF.  Some of these are purely cosmetic, but in the case of filenames the typos actually prevented compilation.  With these changes, `sample.tex` can now be compiled.

### CODE REVIEW

**Comment by augustfly** [comment]
Thanks @adam-m-jcbs. To be clear neither @gregschwarz nor I experienced any compilation problems with the extant `sample.tex` even though you clearly found typos that triggered on one or more latex compilation systems. The image filenames are probably case sensitive OS differences, but i have no idea how a latex engine could work around \girdline but it did. :-)

Can you list your OS/LaTeX engine for us?  I'm using `This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014)` on Mac OSX 10.10.5.

I'm traveling and will merge this once I get back and cascade this merge out of github and into other relevant locations.

**Comment by adam-m-jcbs** [comment]
Indeed, this could be an OS issue regarding case sensitivity.  When I do a fresh pull of the current repo and execute `pdflatex sampe.tex` I get output including this error:

```
Warning: File `RS_oph.eps' not found on input line 820.

! Package pdftex.def Error: File `RS_oph-eps-converted-to.pdf' not found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.820           }
                 
?
```

The output of `pdflatex --version` is (with irrelevant info removed):

```
pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/Arch Linux)
kpathsea version 6.2.1
Compiled with libpng 1.6.21; using libpng 1.6.21
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with poppler version 0.42.0
```

I'm compiling on an Arch Linux system.  The output of `cat /proc/version` is

```
Linux version 4.5.0-1-ARCH (builduser@tobias) (gcc version 5.3.0 (GCC) ) #1 SMP PREEMPT Tue Mar 15 09:41:03 CET 2016
```

I find the same error on a Fedora system.  I hope this clarifies why I'm having the issue.  I expect other Linux users would have similar problems.

**Comment by adam-m-jcbs** [comment]
Regarding the `\girdline` typo, it was only in the text.  In the actual figure markup the correct `\gridline` was used.

**Comment by gregschwarz** [comment]
Are you including "\usepackage{epstopdf}" when you call pdflatex on sample.tex? I have to include that in the preamble for all articles that have .eps files so that they can be converted to pdf. This is what I think your error messages are trying to tell you.  

Also thanks for the \gridline typo. It was pointed out to me a few weeks ago and should be fixed in the version of the main AAS site here: 

http://journals.aas.org/authors/aastex.html. 

I think the github version is still old however.

**Comment by adam-m-jcbs** [comment]
Including `\usepackage{epstopdf}` does not eliminate the error.  It is my understanding (and my experience in practice) that recent (2010+) TeX Live (and MacTeX) versions automatically convert eps files to pdf when needed, with no need to explicitly include `\usepackage{epstopdf}`.

**Comment by augustfly** [comment]
I agree with @adam-m-jcbs -- the best hypothesis is that this [eps file naming] is related to the fact that Macs (which greg and I use) are case insensitive, while Linux distros are case sensitive. I'll accept the merge since it clearly compiles on my Mac. And, no, I don't think we are in a position to run virtualboxes to platform test this.

**Comment by adam-m-jcbs** [comment]
Thanks!  No need to platform test, that's the beauty of github!  I really appreciate y'all (and the others involved) making this all available and maintaining it.  This is an excellent update of the AASTeX package.  And the sample.tex document makes diving in very easy.

**Pull request merged**
